nvisits : 2390000 #total number of LSST visits - 10 years
Fields: ['COSMOS','ELAIS','CDFS','XMM-LSS','ADFS']
COSMOS :
  seasonlength: 4.9 #season length [ months]
  cadence: 1 #cadence [days]
  nseasons: 2 #number of seasons
  nvisits: 232 #number of visits per obs night
  zlim: 0.9 #redshift limit
  npointings: 1
XMM-LSS :
  seasonlength: 5.4 #season length [ months]
  cadence: 1 #cadence [days]
  nseasons: 2 #number of seasons
  nvisits: 232 #number of visits per obs night
  zlim: 0.9 # redshift limit
  npointings: 1
CDFS:
  seasonlength: 6. #season length [ months]
  cadence: 1 #cadence [days]
  nseasons: 2 #number of seasons
  nvisits: 27 #number of visits per obs night
  zlim: 0.5
  npointings: 1
ELAIS:
  seasonlength: 6. #season length [ months]
  cadence: 1 #cadence [days]
  nseasons: 2 #number of seasons
  nvisits: 27 #number of visits per obs night
  zlim: 0.5
  npointings: 1
ADFS:
  seasonlength:  6. #season length [ months]
  cadence: 1 #cadence [days]
  nseasons: 4 #number of seasons
  nvisits: 27 #number of visits per obs night
  zlim: 0.5
  npointings: 1
AGN:
  seasonlength:  6.0  #season length [ months]-could be 5.25
  cadence: 2 #cadence [days]
  Nfields: 4 #number of fields per season
  nseasons: 10 #number of seasons	
  nvisits: 18 #number of visits per obs night - see AGN paper