frac_DDF : 0.06 #DDF fraction
Nvisits : 2390000 #total number of LSST visits - 10 years
COSMOS :
  season_length: 6. #season length [ months]
  cadence: 1 #cadence [days]
  Nfields: 1 #number of fields per season
  Nseasons: 10 #number of seasons
  Nvisits: 45 #number of visits per obs night
DDF_not_COSMOS:
  season_length:  6. #season length [ months]
  cadence: 1 #cadence [days]
  Nfields: 5 #number of fields per season
  Nseasons: 10 #number of seasons
  Nvisits: 45 #number of visits per obs night
AGN:
  season_length:  6.0  #season length [ months]-could be 5.25
  cadence: 2 #cadence [days]
  Nfields: 4 #number of fields per season
  Nseasons: 10 #number of seasons	
  Nvisits: 18 #number of visits per obs night - see AGN paper